version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "redis-server"
      - "mongo-server"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis-server
      - MONGO_URL=mongo://mongo-server
  mongo-server:
    image: 'mongo'
  redis-server:
    image: 'redis'
